spring:
  main:
    banner-mode: off
    web-application-type: none # change to 'reactive' for development
  cloud:
    function:
      preferred-json-mapper: jackson
      web:
        export:
          enabled: false
          debug: false
      aws:
        custom: true
      definition: exampleFunction
debug: false

management:
  endpoint:
    web:
      exposure:
        include: functions

aws:
  region: ap-southeast-2